// Copyright (C) 2023  Egon Willighagen
// License: MIT

// groovy createMarkdown.groovy *.json

import groovy.json.JsonSlurper
import groovy.io.FileType

println """<img width="300" align="right"
     alt="VHP4Safety logo" 
     src="VHP-LOGO-100mm-RGB.png">
# VHP4Safety Cloud Services

<!-- THIS FILE IS AUTOGENERATED. DO NOT EDIT. -->

VHP4Safety needs a cloud with a high diversity of services to support their case studies.
The services will run on (interal) but also outside (external) the VHP4Safety cloud,
on a case by case basis.

This webpage gives an overview of the VHP4Safety Cloud Services on the Production and
Development platforms. The second is where we develop and test cloud services, while the
first runs a stable version of the service.

Below you find an overview of services available in the context of the VHP4Safety Platform.
[Additional services have been suggested](https://github.com/VHP4Safety/cloud/labels/service)
and users can [request additional services](https://github.com/VHP4Safety/cloud/issues/new/choose).

## Cloud catalog

The VHP4Safety Cloud catalog of potential, internal, and external services is
available [here](catalog.md).

## Production VHP4Safety Platform

There currently is no production platform yet.
"""

println """## Development VHP4Safety Platform

The current development platform runs several services.
"""

def list = []

def dir = new File("service")
dir.eachFileRecurse (FileType.FILES) { file ->
  if (file.name.endsWith(".json") && file.name != "template.json") {
    list << file
  }
}
list = list.sort()

list.each { file ->
  fileContents = file.text
  def data = new JsonSlurper().parseText(fileContents)
  logo = ""
  if (data.instance && (data.instance.type == "VHP4Safety") && (data.instance["vhp-platform"] == "Development")) {
    if (data.screenshot) logo = "<img width=\"150\" align=\"right\"\n     alt=\"screenshot of the service\" \n     src=\"service/${data.screenshot}\">"
    println """${logo}
### ${data.service}

${data.description} [[more info](service/${data.id}.md)]

"""
  }
}

println """
## External Services

"""

list.each { file ->
  fileContents = file.text
  def data = new JsonSlurper().parseText(fileContents)
  logo = ""
  if (data.instance &&
      (((data.instance.type == "VHP4Safety") && (data.instance["vhp-platform"] == "External")) ||
       (data.instance.type == "VHP4Safety Selection"))) {
    if (data.screenshot) logo = "<img width=\"150\" align=\"right\"\n     alt=\"screenshot of the service\" \n     src=\"service/${data.screenshot}\">"
    println """${logo}
### ${data.service}

${data.description} [[more info](service/${data.id}.md)]

"""
  }
}

println """
### Funding

VHP4Safety – the Virtual Human Platform for safety assessment project
[NWA 1292.19.272](https://www.nwo.nl/projecten/nwa129219272) is part of the NWA
research program ‘Research along Routes by Consortia (ORC)’, which is funded by the Netherlands Organization
for Scientific Research (NWO). The project started on June 1, 2021 with a budget of over 10 million Euros
and will last for the duration of 5 years. 
"""
